name: test

channels:
  - conda-forge
  - defaults

dependencies:
  - openblas
  - mkl
  - libopenblas
  - libblas
  - liblapack
  - openmp
  - meson
  - ninja
  - numpy
  - pip
  - python
  - pkg-config
  - setuptools
