!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.26.2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitHAMS_Full(f2pysetupfunc)
      use HAMS_Full, only : Exec
      external f2pysetupfunc
      call f2pysetupfunc(Exec)
      end subroutine f2pyinitHAMS_Full


