!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.26.2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinithams_full(f2pysetupfunc)
      use hams_full, only : exec
      external f2pysetupfunc
      call f2pysetupfunc(exec)
      end subroutine f2pyinithams_full


